[package]
name = "libmuffintin-radial"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "muffintin_radial"

[dependencies]
libmuffintin-core = { path = "../mt-core" }
thiserror.workspace = true

[lints]
workspace = true
