[package]
name = "libmuffintin-lapw"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "muffintin_lapw"

[dependencies]
libmuffintin-core = { path = "../mt-core" }
libmuffintin-envelope = { path = "../mt-envelope" }
libmuffintin-operators = { path = "../mt-operators" }
libmuffintin-sphere = { path = "../mt-sphere" }
libmuffintin-recipes = { path = "../mt-recipes" }
libmuffintin-tensor = { path = "../mt-tensor" }
num-complex.workspace = true
thiserror.workspace = true

[lints]
workspace = true
