#!/usr/bin/env python3
"""Regenerate STATUS.md from ledger state lines, plan headers, and the main tip.

Usage, from the harness worktree root:

    python3 update-status.py          # rewrite STATUS.md
    python3 update-status.py --check  # exit 1 if STATUS.md is stale

Inputs:
- ledger.md: entry headings ``## <date> · <evt|evd>-NNNN · <title>`` and, inside
  an entry, ``- state: <workstream> = <state>`` and ``- note: <workstream> = <text>``.
  The last state and note per workstream win.
- plans/<workstream>/plan.vN.md headers: ``- Workstream ID:``, ``- Plan version:``,
  ``- Approval:``. The highest version per workstream is shown.
- ``git rev-parse main`` in the shared repository, when available.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent
HEAD_RE = re.compile(r"^## (\d{4}-\d{2}-\d{2}) · ((?:evt|evd)-\d{4}) · (.+)$")
STATE_RE = re.compile(r"^- state: (\S+) = (.+?)\s*$")
NOTE_RE = re.compile(r"^- note: (\S+) = (.+?)\s*$")


def parse_ledger(path):
    entries, states, notes = [], {}, {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = HEAD_RE.match(line)
        if match:
            entries.append(match.groups())
            continue
        match = STATE_RE.match(line)
        if match:
            states[match.group(1)] = match.group(2)
            continue
        match = NOTE_RE.match(line)
        if match:
            notes[match.group(1)] = match.group(2)
    return entries, states, notes


def parse_plans(root):
    plans = {}
    for path in sorted((root / "plans").glob("*/plan.v*.md")):
        workstream = version = approval = None
        for line in path.read_text(encoding="utf-8").splitlines()[:25]:
            if line.startswith("- Workstream ID:"):
                workstream = line.split("`")[1]
            elif line.startswith("- Plan version:"):
                version = int(line.split(":", 1)[1])
            elif line.startswith("- Approval:"):
                approval = line.split(":", 1)[1].strip()
        if workstream is None or version is None:
            continue
        if workstream not in plans or version > plans[workstream][0]:
            plans[workstream] = (version, path.relative_to(root).as_posix(), approval or "unknown")
    return plans


def short(text):
    return re.split(r"[;(]", text, maxsplit=1)[0].strip()


BASELINE_RE = re.compile(r"^- Code baseline: (.+)$")


def main_tip(root):
    """Return the `main` baseline text: live from git when a main ref is visible,
    otherwise carried over from the existing STATUS.md (the MSI mirror sees no
    main ref and its git dir is not visible from WSL Python)."""
    for ref in ("main", "origin/main", "github/main"):
        try:
            sha = subprocess.check_output(
                ["git", "rev-parse", "--verify", "--quiet", ref], cwd=root, text=True,
                stderr=subprocess.DEVNULL).strip()
            date = subprocess.check_output(
                ["git", "log", "-1", "--format=%cs", ref], cwd=root, text=True,
                stderr=subprocess.DEVNULL).strip()
            if sha:
                return f"`main` at `{sha}` ({date})"
        except (OSError, subprocess.CalledProcessError):
            continue
    status = root / "STATUS.md"
    if status.exists():
        for line in status.read_text(encoding="utf-8").splitlines():
            match = BASELINE_RE.match(line)
            if match:
                return match.group(1)
    return "`main` tip not available in this checkout"


def render(entries, states, notes, plans, baseline):
    last = f"{entries[-1][1]} ({entries[-1][0]})" if entries else "none"
    lines = [
        "# Status",
        "",
        "Generated by `update-status.py` from `ledger.md` state lines, plan headers,",
        "and the `main` tip. Do not edit by hand; append to the ledger instead.",
        "`ledger.md` and the live `main` worktree are authoritative.",
        "",
        f"- Code baseline: {baseline}",
        f"- Last ledger entry: {last}",
        "",
        "| Workstream | State | Plan | Notes |",
        "|---|---|---|---|",
    ]
    for workstream in sorted(set(states) | set(plans)):
        state = states.get(workstream, "no ledger state line")
        if workstream in plans:
            _, path, approval = plans[workstream]
            plan = f"`{path}`, {short(approval)}"
        else:
            plan = "none"
        lines.append(f"| `{workstream}` | {state} | {plan} | {notes.get(workstream, '')} |")
    return "\n".join(lines) + "\n"


def main(argv):
    entries, states, notes = parse_ledger(ROOT / "ledger.md")
    text = render(entries, states, notes, parse_plans(ROOT), main_tip(ROOT))
    target = ROOT / "STATUS.md"
    if "--check" in argv:
        current = target.read_text(encoding="utf-8") if target.exists() else ""
        if current != text:
            sys.stderr.write("STATUS.md is stale; run update-status.py\n")
            return 1
        return 0
    target.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
