[package]
name = "libmuffintin-envelope"
description = "Plane-wave envelope evaluation for muffin-tin methods"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "muffintin_envelope"

[dependencies]
libmuffintin-core = { path = "../mt-core" }
libmuffintin-sphere = { path = "../mt-sphere" }
num-complex.workspace = true
thiserror.workspace = true

[lints]
workspace = true
