[package]
name = "libmuffintin-sphere"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "muffintin_sphere"

[dependencies]
libmuffintin-core = { path = "../mt-core" }
num-complex.workspace = true
rayon.workspace = true
thiserror.workspace = true

[lints]
workspace = true
