[package]
name = "libmuffintin-mpb"
description = "SPEX-compatible mixed product basis constructor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
libmuffintin-basis = { path = "../libmuffintin-basis" }
libmuffintin-core = { path = "../mt-core" }
libmuffintin-envelope = { path = "../libmuffintin-envelope" }
libmuffintin-operators = { path = "../libmuffintin-operators" }
libmuffintin-product = { path = "../libmuffintin-product" }
libmuffintin-radial = { path = "../mt-radial" }
num-complex.workspace = true
thiserror.workspace = true

[lints]
workspace = true
