name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TBLIS_SRC: https://github.com/MatthewsResearchGroup/tblis.git
      TBLIS_VER: eb719e718976572e0ab53975f4e0c799faeb35f2
      CC: gcc
      CXX: g++
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Formatting
        run: cargo fmt --all --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Tests
        run: cargo test --workspace --all-targets
